### PR TITLE
Test the latest Django and Python versions

### PR DESCRIPTION
**Pull request by dwaynebailey**
* Use ~= to make sure we testing the latest Django without needing to adjust the config
* Test Python 3.6

### CODE REVIEW

**Comment by ubernostrum** [comment]
This doesn't work because of how the "compatible" version comparison is specified: `pip install Django~=1.8` will install Django 1.10.6, for example, because the version algorithm considers 1.10 and 1.8 to be compatible releases.

I'm working on a different approach that avoids the need for version updates except when Django issues a new feature release series (i.e., 1.10 -> 1.11).

**Comment by dwaynebailey** [comment]
@ubernostrum not sure I follow, since the micro version is already included `~=` is in fact working correctly.  But I'll wait to see you alternate approach.

**Comment by ubernostrum** [comment]
Have a look at 7c148f88dbeec9ae1258e2504d4edab493d788d3 which revamps the whole way tests get run.

**Comment by dwaynebailey** [comment]
@ubernostrum yip just saw that, the previous was elegantly clean and simple, not so sure about the new one.

**Comment by ubernostrum** [comment]
The Makefile approach is something I'm trying out because it makes it ludicrously easy to spin up testing environments with just a couple commands; I can script a loop of `make venv test teardown` to run my own local build matrix, for example (and so can anyone else!).

**Pull request closed without merging**
