### PR TITLE
Travis button, for easy test status discovery

### PR DESCRIPTION
**Pull request by doismellburning**
("Includes" / branched from https://github.com/ubernostrum/django-contact-form/pull/1 for the rendering support)

### CODE REVIEW

**Comment by ubernostrum** [comment]
For the moment I'm avoiding putting the Travis badge up. Might come back to this later, though.

**Comment by doismellburning** [comment]
If you recall, moldy had trouble navigating to the test output due to lack of familiarity with Travis; it strikes me as something nice to lower the bar for potential new users / contributors

**Comment by ubernostrum** [comment]
The main reason is that I'm planning to roll a release in the next couple days, and I don't like having the Travis status badge in the release version of the README, so I tend to remove it right around that time and put it back afterward.

**Comment by doismellburning** [comment]
Ah, that's a good point I hadn't really considered, thanks!

**Pull request closed without merging**
